[package]
name = "apix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-rc.8", features=["regex", "cargo"] }
clap_generate = "3.0.0-rc.8"
regex = "1.3.4"
url = "2.1.1"
lazy_static = "1.4.0"
strum = "0.23.0"
strum_macros = "0.23.1"
openapiv3 = "1.0.0-beta.2"
serde_json = "1.0.48"
serde_yaml = "0.8.11"
reqwest = { version="0.11.6", features = ["gzip"] }
tokio = { version = "1.12.0", features = ["full"] }
anyhow = "1.0.26"
serde = "1.0.104"
indexmap = "1.3.2"
async-trait = "0.1.51"
bat = "0.18.3"
dirs = "4.0.0"
whoami = "1.2.1"
chrono = "0.4.19"

[dev-dependencies]
test-case = "1.2.1"
