---
apiVersion: apix.io/v1
metadata:
  name: github-upload-release-asset
  labels:
    app: apix
    apix.io/api: github
  annotations:
    apix.io/created-by: ecyrbe
    apix.io/created-at: "2022-01-12T20:00:09.830263999+00:00"
    apix.io/body-file: "../target/release/{{ env.ASSET }}"
kind: Request
spec:
  request:
    method: POST
    url: https://uploads.github.com/repos/{{ env.GITHUB_REPOSITORY }}/releases/{{ env.RELEASE_ID }}/assets
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/gzip
      authorization: Bearer {{ env.GITHUB_TOKEN }}
    queries:
      name: "{{ env.ASSET }}"
