# example to execute this request:
# apix exec postman-echo-post-file
apiVersion: apix.io/v1
metadata:
  name: postman-echo-post-file
  annotations:
    apix.io/body-file: ../docs/logo.svg
kind: Request
spec:
  request:
    method: post
    url: https://postman-echo.com/post
    headers:
      accept: application/json
      content-type: image/svg+xml
    queries:
      param1: value1
      param2: value2
