# example to execute this request:
# apix exec -f ./examples/request.yaml
apiVersion: apix.io/v1
metadata:
  name: test
  annotations:
    apix.io/convert-body-string-to-json: "true"
kind: Request
spec:
  parameters:
    - name: todo
      required: true
      schema:
        type: integer
    - name: email
      required: true
      schema:
        type: string
        format: email
  context:
    # you can create new variables in the context
    url: https://jsonplaceholder.typicode.com/todos
    # you can use variables from parameters in the context
    next: "{{ parameters.todo + 1 }}"
    # you can use variables from introspection in the context
    annotation: '{{ manifest.metadata.annotations["apix.io/convert-body-string-to-json"] }}'
    # you cannot use variables created in the context
    # error: "{{ next + 1 }}" # variable next is not defined in context itself
  request:
    method: get
    # you can use variables from the context
    url: "{{ context.url }}/{{ context.next }}"
    headers:
      accept: application/json
    # you can use variables from the process environnement
    body: |-
      {
        "user": "{{ env.USERNAME }}",
        "original": {{ parameters.todo  }},
        "hello": "{{ parameters.email }}",
        "annotation": "{{ context.annotation }}"
      }
