# example to execute this request:
# apix exec -f ./examples/request.yaml
apiVersion: apix.io/v1
metadata:
  name: test
  annotations:
    apix.io/convert-body-string-to-json: "true"
kind: Request
spec:
  parameters:
    - name: todo
      required: true
      schema:
        type: integer
    - name: email
      required: true
      schema:
        type: string
        format: email
  context:
    url: https://jsonplaceholder.typicode.com/todos
  request:
    method: get
    url: "{{url}}/{{ parameters.todo }}"
    headers:
      accept: application/json
    body: |-
      {
        "test": {{ parameters.todo + 1 }},
        "hello": "{{ parameters.email }}",
        "user": "{{ env.USERNAME }}"
      }
