# example to execute this request:
# apix exec request_with_query_params
apiVersion: apix.io/v1
metadata:
  name: request_with_query_params
kind: Request
spec:
  parameters:
    - name: max_results
      required: true
      schema:
        type: integer
        default: 1
        minimum: 1
        maximum: 200
  context:
    # you can create new variables in the context
    url: https://jsonplaceholder.typicode.com/todos
  request:
    method: get
    # you can use variables from the context and parameters
    url: "{{ context.url }}"
    headers:
      accept: application/json
    queries:
      _limit: "{{ parameters.max_results }}"
