name: CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Cargo.lock
      - Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - Cargo.lock
      - Cargo.toml
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        config:
          - do: check format clippy test
            os: ubuntu-latest
          - do: check test
            os: windows-latest
          - do: check test
            os: macos-latest
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          default: true
      - name: check code
        if: contains(matrix.config.do, 'check')
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: check format
        if: contains(matrix.config.do, 'format')
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: static code analysis
        if: contains(matrix.config.do, 'clippy')
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
      - name: test
        if: contains(matrix.config.do, 'test')
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
