name: create apix release
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: build apix
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      # eat your own food. use apix to create a release
      - name: create release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |-
          cd examples
          chmod +x ../target/release/apix
          ../target/release/apix exec github-create-release > result.json
          content=`cat result.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=release::$content"
      - name: create tarball
        run: |-
          cp README.md target/release/README.md
          cp LICENSE target/release/LICENSE
          cd target/release
          tar -zcvf apix-${{github.ref_name}}-ubuntu-linux-x64.tar.gz apix LICENSE README.md
      - name: upload tarball
        id: upload
        run: |-
          cd examples
          ../target/release/apix post https://uploads.github.com/repos/${{ github.repository }}/releases/${{ fromJson(steps.release.outputs.release).id }}/assets -q "name:apix-${{github.ref_name}}-ubuntu-linux-x64.tar.gz" -f ../target/release/apix-${{github.ref_name}}-ubuntu-linux-x64.tar.gz -H "Authorization:Bearer ${{ secrets.GITHUB_TOKEN }}"  -H "Content-Type:application/gzip" -H "Accept:application/vnd.github.v3+json"
